apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: todo-app
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://kulik95.github.io/helm-charts/

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: todo-app
  namespace: flux-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: todo-app
      sourceRef:
        kind: HelmRepository
        name: todo-app
        namespace: flux-system
      interval: 1m0s