apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: helm-charts-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://kulik95.github.io/helm-charts/

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: react-hello-world
  namespace: flux-system
spec:
  interval: 1m0s
  targetNamespace: react-hello-world
  chart:
    spec:
      chart: react-hello-world
      sourceRef:
        kind: HelmRepository
        name: helm-charts-repo
        namespace: flux-system
      interval: 1m0s